apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/depends-on: platform-secrets, linstor-cluster
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: storage
spec:
  project: storage
  sources:
    - repoURL: https://charts.min.io/
      chart: minio
      targetRevision: 5.4.0
      helm:
        releaseName: minio
        values: |
          mode: standalone
          replicas: 1
          drivesPerNode: 1
          existingSecret: minio-auth
          persistence:
            enabled: true
            size: 1Gi
            storageClass: linstor-replicated
          buckets:
            - name: k8s-velero-backups
              policy: none
              purge: false
            - name: cnpg-backups
              policy: none
              purge: false
            - name: seal-outputs
              policy: download
              purge: false
          tls:
            enabled: false
          service:
            type: ClusterIP
            port: 9000
          consoleService:
            type: ClusterIP
            port: 9001
          resources:
            requests:
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
