apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/depends-on: nginx-gateway-fabric
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: networking
spec:
  project: platform-kind
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp.git
    targetRevision: main
    path: gitops/platform-kind/layers/networking/values/gateway-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway-fabric
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: Gateway
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
