apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/depends-on: cert-manager-issuers, gateway-resources
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: networking
spec:
  project: platform-kind
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp.git
    targetRevision: main
    path: gitops/platform-kind/layers/networking/values/grafana-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /status
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
