apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: testapp
  namespace: testgroup-testapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: testapp
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - testgroup-testapp
