apiVersion: apps/v1
kind: Deployment
metadata:
  name: seal-api
  labels: {{- include "seal.labels" (dict "name" "seal-api") | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "130"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: seal-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seal-api
        app.kubernetes.io/instance: {{ .Release.Name }}
        redis-client: "{{ .Values.redisClientLabel }}"
      annotations:
        argocd.argoproj.io/sync-wave: "130"
    spec:
      serviceAccountName: seal-api
      containers:
        - name: seal-api
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.apiPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: seal-api-config
            - secretRef:
                name: seal-api-secret

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ toYaml .Values.resources.api | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
