{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-redis-auth
  labels: {{- include "seal.labels" (dict "name" "keda-redis-auth") | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: password
      name: seal-worker-secret
      key: REDIS_PASSWORD
{{- end }}
