{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: seal-migration
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels: {{- include "seal.labels" (dict "name" "seal-api") | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          envFrom:
            - configMapRef:
                name: seal-api-config
            - secretRef:
                name: seal-api-secret
          command: ["/app", "migrate"]
{{- end }}
