{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: seal-api-secret
  labels: {{- include "seal.labels" (dict "name" "seal-api") | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | default "" | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | default "" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: seal-worker-secret
  labels: {{- include "seal.labels" (dict "name" "seal-worker") | nindent 4 }}
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | default "" | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | default "" | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | default "" | b64enc | quote }}
{{- end }}
