{{- if not .Values.rollouts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: seal-api
  labels: {{- include "seal.labels" (dict "name" "seal-api") | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: seal-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: http
      protocol: TCP
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollouts.stableService }}
  labels: {{- include "seal.labels" (dict "name" "seal-api" "instance" .Release.Name) | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: seal-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollouts.canaryService }}
  labels: {{- include "seal.labels" (dict "name" "seal-api" "instance" .Release.Name) | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: seal-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: http
      protocol: TCP
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: seal-worker
  labels:
    {{- include "seal.labels" (dict "name" "seal-worker") | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: seal-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.service.workerMetricsPort }}
      targetPort: metrics
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: seal-ui
  labels: {{- include "seal.labels" (dict "name" "seal-ui") | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: seal-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.uiPort }}
      targetPort: http
      protocol: TCP
