{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: seal-api
  labels: {{- include "seal.labels" (dict "name" "seal-api") | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: seal-api
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: seal-worker
  labels: {{- include "seal.labels" (dict "name" "seal-worker") | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: seal-worker
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
