apiVersion: v1
kind: ServiceAccount
metadata:
  name: seal-api
  labels: {{- include "seal.labels" (dict "name" "seal-api") | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seal-worker
  labels: {{- include "seal.labels" (dict "name" "seal-worker") | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seal-ui
  labels: {{- include "seal.labels" (dict "name" "seal-ui") | nindent 4 }}
