apiVersion: batch/v1
kind: Job
metadata:
  name: restart-cilium-operator
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: cilium-operator-restart
      securityContext:
        runAsNonRoot: false
        supplementalGroups:
          - 65532
      containers:
        - name: kubectl
          image: bitnamilegacy/kubectl:1.33.4
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities:
              drop:
                - ALL
          command:
            - /bin/sh
            - -c
            - |
              kubectl rollout restart deployment/cilium-operator -n kube-system
              kubectl rollout status deployment/cilium-operator -n kube-system --timeout=300s
