apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-operator-restart
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cilium-operator-restart
  namespace: kube-system
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["cilium-operator"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cilium-operator-restart
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: cilium-operator-restart
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cilium-operator-restart
