---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: piraeus-operator-webhook-cert
  namespace: piraeus-datastore
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: base
spec:
  secretName: piraeus-operator-tls
  duration: 8760h0m0s
  renewBefore: 720h0m0s
  dnsNames:
    - piraeus-operator-webhook-service
    - piraeus-operator-webhook-service.piraeus-datastore
    - piraeus-operator-webhook-service.piraeus-datastore.svc
    - piraeus-operator-webhook-service.piraeus-datastore.svc.cluster.local
  issuerRef:
    name: atlas-ca-issuer
    kind: ClusterIssuer
