apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: base
spec:
  project: platform-kind
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: 3.12.2
      chart: metrics-server
      helm:
        releaseName: metrics-server
        valueFiles:
          - $values/gitops/platform-kind/layers/base/values/metrics-server.yaml
    - repoURL: https://github.com/aldoshkineg/atlas-idp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
