apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-team-seal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "90"
    argocd.argoproj.io/depends-on: postgres-cluster,redis,minio,cert-manager
spec:
  project: workloads
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp
    targetRevision: main
    path: workloads/atlas-team/seal
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: atlas-team-seal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
