apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aldoshkineg-seal
  namespace: argocd
spec:
  project: workloads
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp.git
    targetRevision: main
    path: workloads/aldoshkineg/seal
    directory:
      include: "app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: seal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
