apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: PruneLast=true
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: base
spec:
  project: platform
  source:
    repoURL: https://github.com/argoproj/argo-rollouts
    targetRevision: v1.9.0
    path: manifests/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
