---
extends: default

ignore: |
  apps/seal/charts/seal/templates/
  apps/seal/Taskfile.yml

rules:
  line-length:
    max: 140
    level: warning
  document-start: disable
  truthy:
    check-keys: false
