apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-cm
  namespace: testing
data:
  config.hcl: |
    vault {
      address = "http://vault.vault.svc:8200"
      skip_verify = true
    }

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "platform-read"
        }
      }

      sink "file" {
        config = {
          path = "/vault/.vault-token"
        }
      }
    }

    template {
      destination = "/vault/secrets/app-secrets"
      contents = "{{ with secret \"secret/data/platform/test\" }}{{ range $k, $v := .Data.data }}{{ $k }}={{ $v }}\n{{ end }}{{ end }}"
    }
