services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner-atlas-idp
    restart: always
    network_mode: host
    environment:
      - REPO_URL=https://github.com/aldoshkineg/atlas-idp
      - RUNNER_NAME=atlas-idp-docker-runner
      - LABELS=self-hosted
      - RUNNER_TOKEN=${RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - github-runner-work:/_work
      - github-runner-terraform-cache:/opt/terraform/plugin-cache

volumes:
  github-runner-work:
    name: github-runner-work
  github-runner-terraform-cache:
    name: github-runner-terraform-cache
