# Install NGINX Gateway Fabric Controller via official Helm Chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: networking
spec:
  project: default
  sources:
    - repoURL: ghcr.io/nginx/charts
      targetRevision: 1.4.0
      chart: nginx-gateway-fabric
      helm:
        valueFiles:
          - $values/gitops/platform/layers/networking/values/nginx-gateway-fabric.yaml
    - repoURL: https://github.com/aldoshkineg/atlas-idp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway-fabric
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
