apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: piraeus-operator-webhook-cert
  namespace: piraeus-datastore
  labels:
    app.kubernetes.io/component: piraeus-operator
    app.kubernetes.io/instance: piraeus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: piraeus-datastore
    argocd.argoproj.io/instance: linstor-operator
spec:
  secretName: piraeus-operator-tls
  duration: 87600h
  renewBefore: 3600h
  dnsNames:
    - piraeus-operator-webhook-service.piraeus-datastore.svc
    - piraeus-operator-webhook-service.piraeus-datastore.svc.cluster.local
  issuerRef:
    name: atlas-ca-issuer
    kind: ClusterIssuer
