apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlasteam-seal
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: workloads
  annotations:
    argocd.argoproj.io/sync-wave: "90"
    argocd.argoproj.io/depends-on: postgres-cluster,redis,minio,cert-manager
spec:
  project: workloads
  sources:
    - repoURL: https://github.com/aldoshkineg/atlas-idp.git
      targetRevision: main
      path: apps/seal/charts/seal
      helm:
        values: |
          global:
            imageRegistry: ghcr.io/aldoshkineg
          images:
            api:
              tag: v0.52.0@sha256:99ec467f33c620b0f1df5888c12102377ebcfe93fdba0b9c1510f2d827296358
            worker:
              tag: v0.52.0@sha256:6c4eb85d2bcc549ce41467eb65758d8503de6cc7e7c5a442833af24f18a3b758
            ui:
              tag: v0.52.0@sha256:eb0f50c741fe1b17bc3d6bd30afa1354fb72cfdd294e5f4ab57c3f15bff2484d
          vault:
            enabled: false
          gateway:
            enabled: true
          secrets:
            create: false
          rollouts:
            enabled: true
            trafficRouting:
              httpRoute: seal
          migration:
            enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi
          keda:
            enabled: false
          config:
            postgres:
              user: seal
              db: seal
            otel:
              endpoint: http://alloy.monitoring:4318
    - repoURL: https://github.com/aldoshkineg/atlas-idp
      targetRevision: main
      path: gitops/workloads/atlasteam/seal/resources
      directory:
        recurse: true
        exclude: "{.secret-seed,*.tmpl}"
  destination:
    server: https://kubernetes.default.svc
    namespace: atlasteam-seal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
