apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auth-atlasteam-seal-stub
  namespace: vault
data:
  role: atlasteam-seal
  policies: atlasteam-seal-workloads
  bound_service_account_names: seal
  bound_service_account_namespaces: atlasteam-seal
