apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seal
  namespace: atlasteam-seal
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: seal
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - atlasteam-seal
