apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seal-db
  namespace: seal
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: seal-db
  data:
    - secretKey: username
      remoteRef:
        key: secret/workloads/aldoshkineg/seal
        property: db_username
    - secretKey: password
      remoteRef:
        key: secret/workloads/aldoshkineg/seal
        property: db_password
