apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  project: seal
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp-seal.git
    targetRevision: HEAD
    path: charts/seal
    helm:
      values: |
        vault:
          enabled: false
        secrets:
          postgresPassword: "XCGeXFlNxVYonmOdFOO7WNlfa04WU6RmRc2K6TatzW35mRFid1RmbDnUSdE7aVXA"
          redisPassword: "super-secret-redis"
          minioAccessKey: "minioadmin"
          minioSecretKey: "minioadminpassword"
  destination:
    server: https://kubernetes.default.svc
    namespace: seal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
