apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: seal-prometheus-access
  namespace: monitoring
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: atlasteam-seal
      toPorts:
        - ports:
            - port: "9090"
