apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linstor-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: base
spec:
  project: platform
  sources:
    - repoURL: ghcr.io/piraeusdatastore/piraeus-operator
      chart: piraeus
      targetRevision: 2.10.6
      helm:
        releaseName: piraeus-operator
        valueFiles:
          - $values/gitops/platform/base/values/linstor-operator-values.yaml
    - repoURL: https://github.com/aldoshkineg/atlas-idp.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/aldoshkineg/atlas-idp.git
      targetRevision: main
      path: gitops/platform/base/resources/linstor
  destination:
    server: https://kubernetes.default.svc
    namespace: piraeus-datastore
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: piraeus-operator-validating-webhook-configuration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
