apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: PruneLast=true
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: base
spec:
  project: base
  source:
    repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    targetRevision: v8.6.0
    path: client/config/crd
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
