apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: nginx-gateway-fabric
spec:
  secretName: argocd-cert
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - atlas-idp
  dnsNames:
    - argocd.atlas
  issuerRef:
    name: dev-ca-issuer
    kind: ClusterIssuer
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: platform-gateway
      namespace: nginx-gateway-fabric
      sectionName: https-argocd
  hostnames:
    - argocd.atlas
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
