apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
  namespace: nginx-gateway-fabric
spec:
  secretName: vault-cert
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - atlas-idp
  dnsNames:
    - vault.atlas
  issuerRef:
    name: dev-ca-issuer
    kind: ClusterIssuer
