---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBZdn44i7h9mopOxmq/QAinxrhJZNoUXg2EyKixpdvFKxLRYsex5TssOBce1YafxJdoWoO/KULfhCNghm4nALum1m2j0SDgO+pW32F7SCVVmkJjfx7IbADoPg7W/6tBS+aswBduaGcYZA32VrYdkItsBZ8tDctw4piAtPQao1+RXOEA3XEQW4/g+FJW0umAW/Ev3LxJI5iNpVvjQ8YfDeBHJTnTBUXOe6LjawQ8IU5l/WQLCBH/MCiucdifX9v6zOdZkOEUD3o12ugRgXJHhm/6YJv9H3t8fOv5athfdpMNUFnqSKtvK0SFSzZuZ8P1QKO9esnc0TWo3lKFbiyOwmTws7RL98qTyT2xz9Z07KkP5utbWaLOpVcrZW9aWs8ZZ792RTpBVtHbDz/h/hdIDr4DP0GjgtETyKhJuhyTJx29PmVDw8sWkSoOP/hd6rJZALpMHatG1VsxtwQP0RRi6UGdg0N7aGgIsoeVlCmpeO5JwMoJ8Xzx+zupqiWDfooWj3bbL/DykmFiJOlW3Vt7cWW+l1E8V1KaFhzdfL1zA/h5OGQLO41CwziCRyxeKQTaIzE10iGtu1x/+dXanIcLyatflPBCGWdSKcB/xK6jfwLxXlZhcmDJmSPsVtFuXN+VbcI0OcDQWeHnQSEqaiJQIx4X7xAgzt6igEiTVIVB5L5za843O/7A6KhdJ6SkQGTsWvFs5TqHxhzPLBhq/doifuTGTa0=
  template:
    metadata:
      name: redis-auth
      namespace: redis
