apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seal-s3
  namespace: seal
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: seal-s3
  data:
    - secretKey: accessKey
      remoteRef:
        key: secret/workloads/aldoshkineg/seal
        property: minio_access_key
    - secretKey: secretKey
      remoteRef:
        key: secret/workloads/aldoshkineg/seal
        property: minio_secret_key
