apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dev-ca-issuer
spec:
  ca:
    secretName: dev-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-tls-cert
  namespace: nginx-gateway-fabric
spec:
  secretName: platform-tls-cert
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - Com
    countries:
      - RU
    provinces:
      - Moscow
    localities:
      - MSK
  commonName: "*.atlas"
  dnsNames:
    - "*.atlas"
    - "localhost"
    - "*.localhost"
  issuerRef:
    name: dev-ca-issuer
    kind: ClusterIssuer
