name: Terraform EKS (stub)

runs:
  using: composite

  steps:

    - name: EKS not implemented yet
      run: |
        echo "EKS pipeline is not implemented yet"
        echo "This is a stub workflow"
