apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seal-cert
  namespace: kube-system
spec:
  secretName: seal-cert
  issuerRef:
    name: atlas-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - seal.atlas
