apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: production-db-backup
  namespace: database
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: production-db-backup
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: secret/platform/minio
        property: rootUser
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: secret/platform/minio
        property: rootPassword
