apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitors
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/depends-on: kube-prometheus-stack
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: observability
spec:
  project: observability
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp.git
    targetRevision: main
    path: gitops/platform/observability/resources/monitor
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
