apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: platform-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    template:
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/platform/grafana
        property: admin-password
