apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-auth
  namespace: redis
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: redis-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: redis-password
      remoteRef:
        key: secret/platform/redis
        property: redis-password
