apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-hostpath
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: storage
spec:
  project: default
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp.git
    targetRevision: main
    path: gitops/platform/layers/storage/values/csi-hostpath
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m