apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linstor-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/depends-on: linstor-operator
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: storage
spec:
  project: platform
  source:
    repoURL: https://piraeusdatastore.github.io/helm-charts
    chart: linstor-cluster
    targetRevision: 1.1.1
    helm:
      releaseName: linstor-cluster
      valueFiles:
        - $values/gitops/platform/layers/storage/values/linstor-cluster-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: piraeus-datastore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
