apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/depends-on: postgres-cluster,redis,minio,cert-manager
spec:
  project: seal
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp.git
    targetRevision: HEAD
    path: apps/seal/charts/seal
    helm:
      values: |
        global:
          imageRegistry: ghcr.io/aldoshkineg
        images:
          api:
            tag: v0.25.0
          worker:
            tag: v0.25.0
          ui:
            tag: v0.25.0
        vault:
          enabled: false
        secrets:
          postgresPassword: "MyzuMb6B1plUW0Tbkze7Xe25npzwQ6Uyym3OuFPf7QSgGKbvV5ennoHgPtFyDvGf"
          redisPassword: "e5f2190c315c1afedf9809e7611a1d9d685a17a601966d1d6451a5a6fc93208c"
          minioAccessKey: "atlas-minio-admin"
          minioSecretKey: "3f9c62b0351ec216ed239c607a31147371a56c3fe65585cb72fe2447d586976e"
  destination:
    server: https://kubernetes.default.svc
    namespace: seal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
