apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/depends-on: postgres-cluster,redis,minio,cert-manager
spec:
  project: seal
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp.git
    targetRevision: HEAD
    path: apps/seal/charts/seal
    helm:
      values: |
        vault:
          enabled: false
        secrets:
          postgresPassword: "MyzuMb6B1plUW0Tbkze7Xe25npzwQ6Uyym3OuFPf7QSgGKbvV5ennoHgPtFyDvGf"
          redisPassword: "oVMTZL9K04F/h9m9qjD/5ozI1ulrD9Yj"
          minioAccessKey: "minioadmin"
          minioSecretKey: "minioadminpassword"
  destination:
    server: https://kubernetes.default.svc
    namespace: seal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
