apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: test2
  namespace: atlasteam-test2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: test2
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - atlasteam-test2
