apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auth-atlas-team-seal-stub
  namespace: vault
data:
  role: atlas-team-seal
  policies: atlas-team-seal-workloads
  bound_service_account_names: seal
  bound_service_account_namespaces: atlas-team-seal
