apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: atlasteam-seal-ingress
spec:
  endpointSelector:
    matchExpressions:
      - key: "k8s:io.kubernetes.pod.namespace"
        operator: In
        values:
          - database
          - redis
          - minio
          - monitoring
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": atlasteam-seal
      toPorts:
        - ports:
            - port: "5432"
            - port: "6379"
            - port: "9000"
            - port: "4318"
