apiVersion: v1
kind: ResourceQuota
metadata:
  name: seal-quota
  namespace: atlasteam-seal
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
    persistentvolumeclaims: "5"
    services: "10"
    configmaps: "20"
    secrets: "20"
