apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: observability
spec:
  project: platform-kind
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 68.2.0
      chart: kube-prometheus-stack
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/gitops/platform-kind/layers/observability/values/prom-stack.yaml
          - $values/gitops/platform-kind/layers/observability/values/alert-rules.yaml
          - $values/gitops/platform-kind/layers/observability/values/dashboards.yaml
    - repoURL: https://github.com/aldoshkineg/atlas-idp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /status
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
