apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/depends-on: redis
  labels:
    app.kubernetes.io/component: workload
    app.kubernetes.io/layer: workloads
spec:
  project: workloads
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp.git
    targetRevision: main
    path: apps/charts/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: worker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
