apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: observability
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.9.0
      chart: alloy
      helm:
        releaseName: alloy
        valueFiles:
          - $values/gitops/platform/layers/observability/values/alloy.yaml
    - repoURL: https://github.com/aldoshkineg/atlas-idp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
