name: Install Tools
description: "Install required CLI tools"

runs:
  using: composite
  steps:
    - name: Install required binaries
      shell: bash
      env:
        VAULT_VERSION: "1.18.0"
        TERRAFORM_VERSION: "1.15.3"
        KUBECTL_VERSION: "1.34.0"
        KIND_VERSION: "0.29.0"
        TRIVY_VERSION: "0.70.0"
        YAMLLINT_VERSION: "1.35.1"
      run: |
        chmod +x .github/scripts/install-tools.sh
        .github/scripts/install-tools.sh vault $VAULT_VERSION
        .github/scripts/install-tools.sh terraform $TERRAFORM_VERSION
        .github/scripts/install-tools.sh kubectl $KUBECTL_VERSION
        .github/scripts/install-tools.sh kind $KIND_VERSION
        .github/scripts/install-tools.sh trivy $TRIVY_VERSION
        .github/scripts/install-tools.sh yamllint $YAMLLINT_VERSION

    - name: Verify tools
      shell: bash
      run: |
        vault version
        terraform version
        kubectl version --client
        kind version
        trivy version
        yamllint --version
