# CI cluster — отдельное имя, чтобы не конфликтовать с dev-кластером atlas-idp
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: atlas-idp-ci
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
  - role: worker
