apiVersion: v1
kind: ConfigMap
metadata:
  name: seal-api-config
  labels: {{- include "seal.labels" (dict "name" "seal-api") | nindent 4 }}
data:
  HTTP_PORT: "{{ .Values.service.apiPort }}"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  POSTGRES_HOST: "{{ .Values.config.postgres.host }}"
  POSTGRES_PORT: "{{ .Values.config.postgres.port }}"
  POSTGRES_USER: "{{ .Values.config.postgres.user }}"
  POSTGRES_DB: "{{ .Values.config.postgres.db }}"
  REDIS_HOST: "{{ .Values.config.redis.host }}"
  REDIS_PORT: "{{ .Values.config.redis.port }}"
  MINIO_ENDPOINT: "{{ .Values.config.minio.endpoint }}"
{{- if .Values.config.downloadUrlPrefix }}
  DOWNLOAD_URL_PREFIX: "{{ .Values.config.downloadUrlPrefix }}"
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seal-worker-config
  labels: {{- include "seal.labels" (dict "name" "seal-worker") | nindent 4 }}
data:
  REDIS_HOST: "{{ .Values.config.redis.host }}"
  REDIS_PORT: "{{ .Values.config.redis.port }}"
  MINIO_ENDPOINT: "{{ .Values.config.minio.endpoint }}"
  MINIO_USE_SSL: "{{ .Values.config.minio.useSSL }}"
  WORKER_POLL_INTERVAL_MS: "1000"
  SIGN_CERT_PATH: "/vault/secrets/tls.crt"
  SIGN_KEY_PATH: "/vault/secrets/tls.key"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seal-ui-config
  labels: {{- include "seal.labels" (dict "name" "seal-ui") | nindent 4 }}
data:
  HTTP_PORT: "{{ .Values.service.uiPort }}"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  BACKEND_API_URL: "http://seal-api:{{ .Values.service.apiPort }}"