apiVersion: v1
kind: Secret
metadata:
  name: seal-api-secret
  labels: {{- include "seal.labels" (dict "name" "seal-api") | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: ""
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: seal-worker-secret
  labels: {{- include "seal.labels" (dict "name" "seal-worker") | nindent 4 }}
type: Opaque
data:
  MINIO_ACCESS_KEY: ""
  MINIO_SECRET_KEY: ""
  REDIS_PASSWORD: ""