apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auth-aldoshkineg-seal-stub
  namespace: vault
data:
  role: aldoshkineg-seal
  policies: aldoshkineg-seal-workloads
  bound_service_account_names: seal-api,seal-worker,seal-ui
  bound_service_account_namespaces: seal
