# Mapping for aldoshkineg/seal workload secrets
# Format: <vault-path> <key>=<ENV_VAR_NAME>
secret/workloads/aldoshkineg/seal  db_username=VL_ALDOSHKINEG_SEAL_DB_USERNAME
secret/workloads/aldoshkineg/seal  db_password=VL_ALDOSHKINEG_SEAL_DB_PASSWORD
secret/workloads/aldoshkineg/seal  redis_password=VL_ALDOSHKINEG_SEAL_REDIS_PASSWORD
secret/workloads/aldoshkineg/seal  minio_access_key=VL_ALDOSHKINEG_SEAL_MINIO_ACCESS_KEY
secret/workloads/aldoshkineg/seal  minio_secret_key=VL_ALDOSHKINEG_SEAL_MINIO_SECRET_KEY