package template

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/aldoshkineg/atlas-idp/tools/atlasctl/pkg/config"
)

func GenerateSeed(keys []config.SeedKey) (map[string]string, error) {
	result := make(map[string]string, len(keys))
	for _, k := range keys {
		val, err := generateValue(k.Generator, k.Length)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", k.Name, err)
		}
		result[k.EnvKey] = val
	}
	return result, nil
}

func generateValue(generator string, length int) (string, error) {
	switch generator {
	case "base64":
		b := make([]byte, length)
		if _, err := rand.Read(b); err != nil {
			return "", err
		}
		return base64.StdEncoding.EncodeToString(b), nil
	case "hex":
		b := make([]byte, length)
		if _, err := rand.Read(b); err != nil {
			return "", err
		}
		return hex.EncodeToString(b), nil
	default:
		return "", fmt.Errorf("unknown generator: %s", generator)
	}
}

func SecretSeedEnv(groupUC, appUC string, secrets map[string]string) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("# %s/%s - atlasctl seed environment file\n", groupUC, appUC))
	b.WriteString("# Auto-generated by atlasctl new. Edit values before running atlasctl seed.\n")
	b.WriteString("#\n")
	b.WriteString("# Format: KEY=value\n")
	for k, v := range secrets {
		b.WriteString(fmt.Sprintf("VL_%s_%s_%s=%s\n", groupUC, appUC, k, v))
	}
	return b.String()
}
