apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-ready
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: security
spec:
  project: default
  source:
    repoURL: https://github.com/aldoshkineg/atlas-idp.git
    targetRevision: main
    path: gitops/platform/layers/security/resources/cert-manager-ready
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
