apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-webhook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: security
spec:
  project: default
  source:
    repoURL: ghcr.io/bank-vaults/helm-charts
    chart: secrets-webhook
    targetRevision: 0.4.1
    helm:
      values: |
        replicaCount: 1
        debug: true
        certificate:
          useCertManager: false
          generate: true
        image:
          pullPolicy: IfNotPresent
        env:
          PROVIDER: "vault"
          VAULT_ADDR: "http://vault.vault.svc:8200"
          VAULT_SKIP_VERIFY: "true"
          VAULT_ALLOW_PRIVATE_ADDR: "true"
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status/terminatingReplicas
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
