{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | b64enc | quote }}
{{- end }}
