image:
  repository: ghcr.io/atlas-idp/frontend
  tag: dev
  pullPolicy: IfNotPresent

replicaCount: 1

config:
  backendApiUrl: http://backend-api.backend-api.svc.cluster.local:8080
  logLevel: info

service:
  port: 8081

resources:
  requests:
    cpu: 30m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
