apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-webhook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/depends-on: vault-operator
  labels:
    app.kubernetes.io/component: platform
    app.kubernetes.io/layer: security
spec:
  project: platform-kind
  source:
    repoURL: ghcr.io/bank-vaults/helm-charts
    chart: secrets-webhook
    targetRevision: 0.4.1
    helm:
      releaseName: vault-secrets-webhook
      values: |
        replicaCount: 1
        debug: false
        certificate:
          useCertManager: true
          generate: false
        image:
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
          targetCPUUtilizationPercentage: 80
        env:
          PROVIDER: "vault"
          VAULT_ADDR: "http://vault.vault.svc:8200"
          VAULT_SKIP_VERIFY: "true"
          VAULT_ALLOW_PRIVATE_ADDR: "true"
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-secrets-webhook
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
