apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-unseal-keys
          key: vault-root
          namespace: vault
