apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-auth
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: minio-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: rootUser
      remoteRef:
        key: secret/platform/minio
        property: rootUser
    - secretKey: rootPassword
      remoteRef:
        key: secret/platform/minio
        property: rootPassword
