---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-auth
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgDSfQ1143M32Rl9xQNkwojTb2mX3pHeylasfWAwFUdrYmbJBHFqh0gCVHnrGphwACPxsmBOtQ3GwtGqH7DGXK4wcVc4/jMpDED+IbVGB6/HbrXoRVqAldN2I042+p0hcugtR4CS3Ug+diJAvk0WTugHiJNXa/L4dOp8GOftGsrGm+uWnrlOE+OFI3rfsbYBzIg8semYACdbVfmWlztm+dn5Wvho1emRKqNsF5Ty06pRWI/tRDOKorpQ+wZ8/cUOiZu4Y6Bc608ulGw5RqP3QXvWPxWxs+a1IDk2X6dmfXutDidFOaoScoR5/A7nwHMKk9ixHl0axEgvC61Hbn3LZWlAPWJtOguE+F54hlme7umT9lZO9uACg9D78+LNcTK6LENEXYfG0l80UbjoYDNCCQYeqZ9ZNkxluw1UeBP6g+FGr9Mrj+wuwP7GkL0i50RLROZLHnqZ+r9WmktwCdS3vFBy9U+zoAYzoOMjEWydUNjgJt/fUEMbs0aSoatPNtm8K1WJyBG56g9WRvRIug0UA+5hdjPK5E2O60FQGBcKz5LPAy7DZTyPM1Pao5LpRGEbJl845Gi+3/UKLPJfZHNAA5Mcfnx4HsrM5DlF+37Kqh+4QBKZ2RMPDFFxdu2qiQYSCavmhpBmhthldsbOSytQrHNJTMD7gTwpr+3burTWvZOigzRBW43NN1JgYCcI87hpbnjsh2ZmlAqHLKbS3hjpJSLvCTw=
    rootUser: AgC4KRcBQo/zaVD5J5WJwB/UiG6Bsyiy/XH2McTN2EhV8vEaMcAAuoHopxXuBhPNVG0i2jR0LsmxEC9gKXfqD5pMocYTp2THgLVcN/hCdAGnXlXLcnm439fmjOAmgEW7AaWSol3WtRMGTd95MvEz42qccJ87QdNpVozm3SZqZlu/MqROAkUDMeyhoMmIz/JAdO++QGsMrNJY2cnj/vLf3VvY/Y0xEGCzXRsPf7WWestefBuKc9E95DHAYOtokMIuKILVjzJuTHmKsM8ty8wI/39jdoR07DdoWjIZZCImg9RkEivcism3IjlVF7s9gmXOlPqQNUDb077GFT7P8kyufdu+vGNEh9RXWPUca5ASNIVvt5kVp+9XPGzRmaOEiMUjJeb70pyOIagbazMTHCXSGEtmFM3WMyzyV2GVI89s4C8oqOfYgVDQKoxg0VYgEM1o+Gvxlm9mJc+GxkXxfZgZMGVL2AnVGlkSNC397be4qLCiifkFaskA1axJuaJP1ORR0JpDkwK/UoAqrIQOLo398rU/J4eszgBtClo+daziVGBGXZD7EtKn/j+MAGMb3SSCyNEBHga2figq9nNfK8U8Ba3QkV3MPw2TNEPuHGYWxztitSzq2HNEg6vS94ivrVhO+rRlnIwC5/l/JMiIRhTV02JdJxFHYhfJsR7+iM9Evqb4chBUby7SZ8UkGzie3WwHKAQ0Ng5bAtUNrjAb
  template:
    metadata:
      name: minio-auth
      namespace: minio
