apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cli-cert
  namespace: kube-system
spec:
  secretName: argocd-cli-cert
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - atlas-idp
  dnsNames:
    - argocd-cli.atlas
  issuerRef:
    name: atlas-ca-issuer
    kind: ClusterIssuer
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-cli-route
  namespace: argocd
spec:
  parentRefs:
    - name: platform-gateway
      namespace: kube-system
      sectionName: https-argocd-cli
  hostnames:
    - argocd-cli.atlas
  rules:
    - backendRefs:
        - name: argocd-server
          port: 443
