apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-health-monitor-controller-runner
  labels:
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/name: hostpath.csi.k8s.io
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
