apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-host-path/master/deploy/kubernetes-1.30/hostpath/csi-hostpath-plugin.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-host-path/master/deploy/kubernetes-1.30/hostpath/csi-hostpath-testing.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-host-path/master/deploy/kubernetes-1.30/hostpath/csi-hostpath-driverinfo.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-host-path/master/deploy/kubernetes-1.30/hostpath/csi-hostpath-snapshotclass.yaml
  - 01-attacher.yaml
  - 02-provisioner.yaml
  - 03-resizer.yaml
  - 04-snapshotter.yaml
  - 05-snapshot-metadata.yaml
  - 06-health-monitor.yaml

namespace: storage
