name: Platform CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  ci:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ./.github/actions/tools

      - uses: ./.github/actions/checks

      - uses: ./.github/actions/terraform-incus
        with:
          atlas_ca_crt: ${{ secrets.ATLAS_CA_CRT }}
          atlas_ca_key: ${{ secrets.ATLAS_CA_KEY }}

      - uses: ./.github/actions/vault-seeds
        with:
          vl_minio_root_user: ${{ secrets.VL_MINIO_ROOT_USER }}
          vl_minio_root_password: ${{ secrets.VL_MINIO_ROOT_PASSWORD }}
          vl_redis_password: ${{ secrets.VL_REDIS_PASSWORD }}
          vl_grafana_password: ${{ secrets.VL_GRAFANA_PASSWORD }}
