name: Platform CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  ci:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ./.github/actions/tools

      - uses: ./.github/actions/checks

      - uses: ./.github/actions/terraform-kind
        with:
          dev_ca_crt: ${{ secrets.DEV_CA_CRT }}
          dev_ca_key: ${{ secrets.DEV_CA_KEY }}

      - uses: ./.github/actions/terraform-eks
        if: false
