name: Install Tools

on:
  workflow_call:

env:
  TERRAFORM_VERSION: "1.15.3"
  KUBECTL_VERSION: "1.34.0"
  KIND_VERSION: "0.29.0"
  TRIVY_VERSION: "0.70.0"
  YAMLLINT_VERSION: "1.37.1"

jobs:

  tools:

    runs-on: [self-hosted]

    steps:

      - uses: actions/checkout@v4

      - name: Install required binaries
        run: |

          chmod +x .github/scripts/install-tool.sh

          .github/scripts/install-tool.sh terraform $TERRAFORM_VERSION
          .github/scripts/install-tool.sh kubectl $KUBECTL_VERSION
          .github/scripts/install-tool.sh kind $KIND_VERSION
          .github/scripts/install-tool.sh trivy $TRIVY_VERSION
          .github/scripts/install-tool.sh yamllint $YAMLLINT_VERSION

      - name: Verify tools
        run: |
          terraform version
          kubectl version --client
          kind version
          trivy version
          yamllint --version
