name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    steps:
    - name: Debug Info
      run: |
        echo "Runner is working"
        whoami
        pwd
        ls -la
